version: '3.8'

services:
  frontend-wlist:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    command: node .output/server/index.mjs
